# Comparação de modelagem de dados no DynamoDB: Abordagens A vs B

## 1. Visão geral das abordagens  
- **Abordagem A (normalizada, atual)**: usa chave de partição `PK = id` (identificador do cliente) e chave de ordenação `SK = "MOTOR#<macro>#<categoria>"`. Cada item representa uma combinação única de macro+categoria. Os atributos incluem `macro`, `categoria` e um `payload` com valor e justificativa. Esse modelo permite consultas granulares: é possível usar `KeyConditionExpression` com `begins_with(SK, "MOTOR#macro")` para obter todas as categorias de um macro, ou condição exata para um par macro+categoria. Fan-out por múltiplos macros é obtido fazendo várias consultas, mas cada uma retorna apenas itens específicos por macro.  
- **Abordagem B (desnormalizada, anterior)**: usa `PK = id` e `SK = "MOTOR#<macro>"`. Cada item corresponde a um macro inteiro. O atributo `payload` contém um *map* ou lista de todas as categorias desse macro (p.ex. `{"categoria1":{...}, "categoria2":{...}, …}`). Aqui há apenas um item por macro. Consultas retornam sempre o item completo do macro; não há caminho de chave para filtrar por categoria. Para ler ou atualizar uma categoria, o cliente precisa tratar o item inteiro do macro em código. Esse modelo simplifica a estrutura (poucos itens por cliente) mas sacrifica granularidade. 

## 2. Comparação critério a critério  

- **Desempenho de leitura:** Na abordagem A, cada categoria é um item pequeno. Uma consulta por PK e SK específicos (ou `begins_with` no SK) retorna somente esse item, consumindo poucos RCUs. A AWS ressalta que 1 RCU permite ler até 4 KB em um item fortemente consistente【13†L76-L83】. Como os itens de categoria tendem a ser pequenos, cada leitura costuma custar apenas 1 RCU. Em contrapartida, B armazena todas as categorias num único item grande do macro. Mesmo que se queira apenas uma categoria, é necessário ler o item completo. Como os custos de leitura escalam com o tamanho do item【19†L281-L289】, ler um item de macro (por exemplo dezenas ou centenas de KB) pode gastar dezenas de RCUs, bem acima do necessário para uma única categoria. Além disso, A permite consulta granular: usando `begins_with(SK, "MOTOR#macro")` podemos recuperar apenas as categorias daquele macro【7†L17-L24】. Em B isso não é possível: a única opção é consultar `PK=id, SK=MOTOR#macro`, retornando todas as categorias de uma vez. Em resumo, A tende a ter latência menor e menor volume de dados transferidos por consulta específica (pois lê somente o necessário), enquanto B lê mais dados do que o usuário precisa e pode incorrer em latência extra. Se a aplicação geralmente lê todas as categorias de um macro de uma vez, B faz apenas uma leitura (mas grande); já A pode fazer uma única query que retorna múltiplos itens (pode ser paginada se >1 MB). De qualquer forma, na prática A costuma ser mais eficiente em I/O porque evita transferir bytes desnecessários【19†L281-L289】【13†L76-L83】.  

- **Desempenho de escrita:** A atualização em A incide apenas sobre o item da categoria em questão. Como 1 WCU cobre 1 KB escrito【13†L81-L83】, escrever um item pequeno de categoria (digamos <1 KB) custa apenas 1 WCU. Em B, por outro lado, atualizar uma categoria implica escrever ou atualizar o mapa inteiro de categorias do macro, possivelmente dezenas de KB. Isso aumenta o consumo de WCU proporcionalmente; por exemplo, escrever 1,5 KB exige 2 WCUs【13†L81-L83】. A AWS exemplifica que separar atributos pequenos e frequentes de um item grande evita gastos extras de WCU【19†L281-L289】: análogo ao exemplo do contador de visualizações no blog da AWS, que foi dividido em um item `VideoStats` separado【19†L292-L300】. Ademais, na Abordagem B atualizações concorrentes no mesmo item de macro podem causar sobrescrita indesejada se não usadas expressões condicionais. A AWS recomenda usar locking otimista (atributo de versão + conditional write) ou transações para garantir consistência em cenários concorrentes【15†L25-L33】. Na Abordagem A, como itens de categorias são distintos, atualizações paralelas em categorias diferentes não se impactam (cada `UpdateItem` é atômico para seu item)【15†L19-L24】. Logo, A oferece maior isolamento: só haveria conflito se dois processos editarem exatamente o mesmo par macro+categoria simultaneamente.  

- **Escalabilidade:** Com crescimento de categorias e macros, as limitações do DynamoDB devem ser consideradas. A AWS impõe limite de tamanho de item de 400 KB【8†L10-L18】. Em B, todos os dados de um macro ficam num só item, então se o número de categorias ou o tamanho do payload crescer demais, corre-se o risco de atingir esse limite ou degradar performance. Na Abordagem A cada categoria é um item independente, praticamente sem chance de extrapolar 400 KB em um único item. Em termos de volume de itens, A gera muitos itens (um por categoria), mas DynamoDB suporta milhões de itens por partição (o limit principal é o throughput). Considerando que há pouca concorrência por cliente, não se prevê *hot partition*, mas sim um maior número de operações de leitura/escrita distintas em vez de um item só. Em B, cresce o número de itens por macro (um por macro) e o tamanho de cada item; em A, cresce o número de itens por categoria. Em throughput, A pode requerer múltiplas consultas (fan-out) para ler vários macros – mas isso foi permitido pelo requisito –, enquanto B é uma consulta por macro (que transfere mais dados). Em resumo, A escala melhor com muitas categorias: evita limites de item, embora gere mais itens; B escala pior em item size, embora gere menos itens.  

- **Complexidade de consulta:** A implementação das consultas reflete esses modelos. Na Abordagem A, é preciso concatenar o valor de `macro` e `categoria` no SK e usar condições de range. Por exemplo, para obter as categorias de um macro faz-se `Query PK=id AND begins_with(SK, "MOTOR#<macro>#")`. A AWS recomenda exatamente esse uso de chaves compostas para consultas eficientes【7†L17-L24】. Em B, só se consulta por macro: `Query PK=id AND SK="MOTOR#<macro>"` retorna todas as categorias de uma vez. Não há suporte a `begins_with` sobre a categoria em B, nem a consulta direta por categoria individual. Como não se pode usar *FilterExpression* para simular um `IN`, a Abordagem B exige sempre ler todo o item do macro para filtrar no cliente. Com *fan-out* habilitado, se é preciso consultar vários macros simultaneamente, A fará várias consultas em paralelo (uma por macro), cada uma retornando só as categorias necessárias; B também fará consultas paralelas, mas cada resultado será maior. Do ponto de vista de implementação, A exige gestão de múltiplas queries (por exemplo, iteração sobre a lista de macros); B simplifica nesse sentido (um GetItem por macro). Em termos de uso de `KeyConditionExpression` e `begins_with`, só A aproveita esses recursos de consultas por chave de ordenação【7†L17-L24】.  

- **Flexibilidade evolutiva:** Em A, adicionar uma nova categoria ou atributos em uma categoria envolve criar ou atualizar itens específicos, sem mexer nos demais. Mudar o formato dos dados (ex.: novas colunas no payload) exige alterar cada item relevante, mas de forma isolada. Em B, alterações estruturais (por exemplo, migrar o mapa interno de categorias para outro formato) obrigam a regravar todo o item de cada macro. Por outro lado, B mantém todos os dados de um macro agrupados, o que pode parecer mais simples se sempre for preciso lidar com o macro inteiro. Contudo, em termos de extensibilidade e aderência a novos acessos, A é mais ágil: é fácil adicionar categorias sem reestruturar grandes objetos. A AWS enfatiza que DynamoDB é *schemaless* e orientado a padrões de acesso; assim, modelar dados separadamente conforme uso (como faz A) costuma ser mais adaptável a mudanças do que manter um único documento rígido. Em síntese, A oferece maior independência e granularidade para evoluir o modelo, enquanto B impõe maior acoplamento dos dados.  

- **Custo (RCU/WCU):** Como já mencionado, DynamoDB cobra por capacidade proporcional aos bytes lidos/escritos【13†L76-L83】. Na Abordagem A, leituras parciais de itens pequenos consomem poucos RCUs; por exemplo, ler ~1–4 KB consome apenas 1 RCU【13†L76-L83】. Em B, ler o mesmo pedaço de informação exige ler o item inteiro, potencialmente várias vezes maior, e portanto mais RCUs. O mesmo vale para escrita: se cada payload é modesto, A cobrará pouco WCU por atualização; B cobrará para o item todo. A AWS deixa claro que “os custos de leitura e escrita aumentam com o tamanho do item”【19†L281-L289】. Dessa forma, em A costuma-se pagar menos pela maioria dos padrões de uso típicos (leitura/escrita de categorias individuais). Para cenários de *fan-out* (vários macros), o custo total de A somará o das consultas por macro; em B será o custo de cada item grande. Em geral, A tende a ser mais econômico, pois raramente transfere informações inúteis. B só se iguala se quase sempre for feito *GetItem* de macro completo – mas mesmo assim paga-se por todo o mapa de categorias, independentemente do que se use. Por exemplo, AWS mostra que separar atributos de frequente atualização reduz custos de WCU【19†L281-L289】. Além disso, A evita *read-after-write* desnecessário: atualiza-se apenas o mínimo requerido.  

- **Concorrência e consistência:** Segundo a AWS, operações como `UpdateItem` são atômicas e sempre agem sobre a versão mais recente do item【15†L19-L24】. Contudo, em esquemas *read-modify-write* sem versionamento, pode ocorrer sobrescrita de dados caso ocorram colisões. Na Abordagem A, como cada categoria é um item distinto, concorrências entre categorias diferentes não colidem. Só haveria disputa se dois processos tentassem atualizar a mesma categoria simultaneamente — situação habitual para qualquer banco. Na Abordagem B, várias atualizações concorrentes no mesmo item de macro podem se atropelar, principalmente se cada uma escreve diferentes chaves do mapa. Para evitar perda de dados, a AWS recomenda mecanismos de controle de concorrência (como *conditional writes* com atributo de versão – *optimistic locking* – ou transações)【15†L25-L33】. Em resumo, A tem menor risco de *race conditions* entre categorias diferentes, enquanto B demanda tratamento explícito (uso de condições, transações ou filas) para manter consistência em atualização concorrente. Como o cenário prevê baixa concorrência por cliente, esses riscos são menores, mas ainda assim B impõe maior complexidade/atenção.  

- **Aderência às boas práticas do DynamoDB:** A modelagem da Abordagem A segue recomendações chave do DynamoDB: usa PK/SK compostas orientadas ao padrão de acesso e adota particionamento vertical de itens grandes. Em particular, A explora bem as sort keys para organizar dados hierarquicamente (SK contendo `<macro>#<categoria>`), permitindo consultas eficientes por prefixo【7†L17-L24】. Além disso, está em linha com o conselho de dividir itens grandes em itens menores associados pela mesma PK (“vertical partitioning”)【8†L48-L56】. Em contraste, a Abordagem B concentra muitos atributos em um único item, algo que a AWS desencoraja quando leva a leituras/escritas maiores do que o necessário. O blog oficial destaca que modelos de dados no estilo *relacional* (documentos imensos) são antipadrões em DynamoDB, pois deixam de aproveitar índices e levam a leituras ineficientes【19†L281-L289】【8†L48-L56】. Assim, A evita o anti-padrão de “item inchado” e aproveita corretamente PK/SK; B viola parcialmente a filosofia “access-driven design”, já que não permite buscar por atributo de categoria em query. Em suma, A está mais alinhada às boas práticas (tudo acessível por chave de partição e ordenação), enquanto B sugere modelagem relacional engarrafada em JSON, sem vantagem para consultas.  

## 3. Tabela resumo (Abordagem A vs B)  

| Critério                    | Abordagem A (normalizada)                                                                               | Abordagem B (desnormalizada)                                                                           |
|-----------------------------|---------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
| **Leitura**                 | Lê apenas itens de categorias específicas; menos bytes. Usa *begins_with* no SK (query granular)【7†L17-L24】. Latência baixa quando foco na categoria. | Lê todo o item do macro. Mais bytes transferidos (custa várias RCUs) devido ao payload completo【19†L281-L289】. Não há filtro por categoria; consulta sempre carrega todas. |
| **Escrita**                 | Atualiza apenas o item da categoria. Menos WCU (1 WCU = 1 KB)【13†L81-L83】. Sem conflito entre categorias distintas. | Atualiza o mapa todo do macro. WCU maior (item maior). Conflitos potenciais se updates concorrentes (mesmo item) – exige conditional writes ou transação【15†L25-L33】. |
| **Escalabilidade**          | Muitas categorias = muitos itens, mas cada um pequeno (baixo risco de atingir limite de 400KB). Distribuição de carga por itens. | Crescimento de categorias amplia o tamanho do item (item pode atingir 400KB【8†L10-L18】). Menos itens no total, mas cada item pode ficar muito grande. |
| **Complexidade de query**   | Uso natural de Query com `begins_with(SK, "MOTOR#macro#")` para grupos de categorias【7†L17-L24】. Fan-out por macro via múltiplas queries independentes. | Query por macro retorna item inteiro; sem suporte a `begins_with` para categorias. Fan-out por macro também (uma query por macro), mas sem granularidade. |
| **Flexibilidade**           | Aditivos: inserir nova categoria = novo item; alterar estrutura = aplicar item a item. Mais modular. | Mudanças estruturais afetam item inteiro (mapa). Menos flexível a mudanças incrementais. |
| **Custo (RCU/WCU)**         | Leitura/escrita proporcional ao tamanho do item pequeno. Gasta poucas RCUs/WCUs (até 1KB por 1 WCU)【13†L76-L83】. Economiza por evitar dados supérfluos. | Lê/escreve vários KB de cada vez. Custa muitas RCUs se item grande【13†L76-L83】. Atualizar categoria gasta pelo item todo. Custa mais segundo bytes transferidos【19†L281-L289】. |
| **Concorrência/consistência** | Atualizações em itens isolados (por categoria) não colidem; *UpdateItem* é atômico por item【15†L19-L24】. Risco baixo de sobrescrita em cenários típicos. | Atualizações simultâneas no mesmo item de macro podem colidir; requer controle (condições/transações) para evitar *lost updates*【15†L25-L33】. Mais risco de inconsistência sem estratégia de versionamento. |
| **Boas práticas DynamoDB**   | Segue padrão “access-driven”: chaves compostas e itens menores. Usa “vertical partitioning”【8†L48-L56】 e chaves de ordenação eficientes【7†L17-L24】. Evita anti-padrões de item inchado. | Concentra muitos atributos em um item. Não permite consultas por atributo interno. Menos alinhada a uma modelagem NoSQL por acesso; comporta-se como um banco relacional embutido. |

## 4. Principais riscos  
- **Abordagem A:** *Volume de itens*: com muitas categorias+macros, pode gerar dezenas ou centenas de itens por cliente. É preciso cuidar da paginação de consultas (limite de 1 MB por resposta). Se o total de itens lidos for grande, será necessário iterar em páginas no código. Porém, esse é um risco gerenciável (basta reconhecer e implementar loop de consulta). *Complexidade de fan-out*: ler várias macros exige rodar várias queries, o que pode aumentar a latência total (embora possa ser paralelizado no cliente). Fora isso, não há perigo de estouro de item, mas a aplicação deve lidar adequadamente com carga extra de chamadas.  
- **Abordagem B:** *Tamanho de item*: conforme categorias crescem, o item de macro pode se aproximar do limite de 400 KB【8†L10-L18】, o que leva a validações falhando ou custos altos. *Sobrescrita concorrente*: sem controle, dois updates concorrentes no mesmo item de macro podem sobrescrever mutuamente. É necessário implementar condicional/versão (otimistic locking) para mitigar – complicando o código. *Ineficiência de I/O*: mesmo ao ler ou escrever parte dos dados, paga-se por todo o payload. Isso pode levar a gastos de capacidade desnecessários (pequenos ganhos compensam com sobrecarga). *Falta de granularidade*: se surgir necessidade de buscar apenas certas categorias, não há índice apropriado; poder-se-ia ter que reescrever a modelagem. Em suma, B traz riscos ocultos de desempenho e escalabilidade que não são imediatamente visíveis no código, mas que surgem com o crescimento dos dados.  

## 5. Decisão final  
Em um cenário de produção conforme descrito, a **Abordagem A (normalizada)** é a mais adequada. Tecnicamente, ela reduz latência e custos ao ler/gravar apenas o mínimo necessário, permite consultas granulares por categoria e cresce de forma mais robusta (evitando limites de tamanho de item)【19†L281-L289】【8†L10-L18】. Além disso, sua estrutura se alinha às boas práticas do DynamoDB (“access-driven design” e particionamento vertical)【7†L17-L24】【8†L48-L56】. A abordagem B, embora simples, apresenta trade-offs críticos: elevado custo de I/O, riscos de sobrescrita concorrente e pouca flexibilidade de consulta, todos difíceis de justificar dada a baixa concorrência por cliente. Portanto, A é escolhida sem hesitação técnica.  

A Abordagem B só seria válida em cenários muito específicos: por exemplo, se o número de categorias fosse muito pequeno (e estático) e o acesso fosse **sempre** ao item completo do macro, de modo que ler o item inteiro não fosse oneroso. Em sistemas onde macros raramente mudam e a simplicidade de um documento único é preferida sobre performance, B poderia ser considerada (embora deva ficar claro que isso sacrifica escalabilidade e custo). Em contraste, quando há necessidade de consultar categorias isoladas ou de lidar com milhares de categorias no futuro, A se mantém recomendada.  

## 6. Recomendações práticas para produção  
Para a Abordagem A adotada, sugerem-se as seguintes práticas:  
- **Usar `UpdateItem` com expressões de atributo** em vez de `PutItem` para atualizações de categoria. Assim, modifica-se apenas o campo necessário, evitando sobrescrever atributos não relacionados. Usar *ConditionExpression* (otimistic locking) se houver risco de concorrência crítica, conforme recomendado pela AWS【15†L25-L33】.  
- **Monitorar consumo e tamanho de itens**. Habilite `ReturnConsumedCapacity` nas operações de escrita/leitura e avalie se os itens de categoria estão crescendo próximo de 400 KB【8†L20-L25】. Essa métrica permite alertar antes de atingir o limite de item. Caso algum item se aproxime demais desse limite, considere particioná-lo verticalmente (criar itens adicionais) ou mover dados raramente usados para outro local.  
- **Provisionamento/adaptabilidade**. Como a carga por cliente é baixa, pode-se usar modo on-demand ou habilitar *auto scaling* para ajustar RCU/WCU dinamicamente. Isso garante disponibilidade sem superdimensionamento.  
- **Consulta em paralelo**. Para leituras envolvendo vários macros (fan-out), realize consultas Query paralelas (uma por macro) para reduzir latência total. Considere usar operações em lote (BatchGetItem) quando apropriado para reduzir chamadas de rede.  
- **Projeção de atributos**. Embora o DynamoDB ainda cobre todas as 4 KB mesmo com `ProjectionExpression` (sem redução de RCU【11†L211-L214】), filtrar dados em nível de aplicação pode diminuir a quantidade de bytes trafegados na rede e agilizar o parsing dos resultados.  
- **Paginação**. Verifique o atributo `LastEvaluatedKey` nas consultas e implemente paginação quando a resposta exceder 1 MB. Lembre-se de iterar até obter todos os itens desejados.  
- **Melhorias futuras**. Se houver necessidade de novos padrões de acesso (ex.: buscar por atributos que não são chave), avalie criar *Global Secondary Indexes* apropriados. No entanto, evite abordar problemas de consulta usando *Scan* ou *FilterExpression*, que são proibidos.  
- **Backups e streams**. Utilize backups e, se necessário, DynamoDB Streams para sincronização ou auditoria. Embora não sejam estritamente parte da modelagem, dão robustez ao sistema.  

Em resumo, mantendo a Abordagem A, priorize monitorar o crescimento dos itens e o uso de capacidade, e aplique estratégias de atualização atômica e queries eficientes, garantindo assim um sistema escalável e de alto desempenho em produção. 

**Fontes:** Documentação e blog da AWS DynamoDB【19†L281-L289】【7†L17-L24】【8†L10-L18】【13†L76-L83】【15†L19-L24】, ilustrando conceitos de custo, dimensões de item, e melhores práticas citadas acima.