version: "3.9"

services:

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs,dynamodb
      AWS_DEFAULT_REGION: us-east-1
      LS_LOGS: trace
      DEBUG: 1
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d